#!/bin/sh

source /jffs/scripts/vlans/helpers.sh

case $1 in
    "restart")
        case $2 in
            "wireless")
                sleep 1
                remove_guest_wifis_from_br0
                add_guest_wifis_to_network_bridges
                update_nvram
                restart_eapd
            ;;

            "firewall")
                flush_ebtables
            ;;

    esac
    ;;

esac
